# Generated by Django 2.2.17 on 2021-01-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='comment',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
