# Generated by Django 2.2.17 on 2021-01-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
