# Generated by Django 2.2.17 on 2021-01-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20210111_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='time',
            field=models.TimeField(default='10:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='date',
            field=models.DateField(),
        ),
    ]
