# Generated by Django 2.2.17 on 2021-01-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='map',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'The Skeld'), (2, 'Polus'), (3, 'MiraHQ'), (4, 'The Airship')]),
        ),
    ]
