# Generated by Django 2.2.17 on 2021-01-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_auto_20210117_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
