# Generated by Django 2.2.17 on 2021-01-19 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_room_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='date_time',
        ),
    ]
