# Generated by Django 2.2.17 on 2021-02-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_remove_room_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='date',
        ),
        migrations.RemoveField(
            model_name='room',
            name='time',
        ),
        migrations.AddField(
            model_name='room',
            name='datetime',
            field=models.DateTimeField(default='2006-10-25 14:30:59'),
            preserve_default=False,
        ),
    ]
