# Generated by Django 2.2.17 on 2021-02-09 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_auto_20210209_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='datetime',
            new_name='game_start',
        ),
    ]
