# Generated by Django 2.2.17 on 2021-02-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0016_auto_20210220_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[('', '----'), (1, 'Beginner'), (2, 'Medium'), (3, 'Advanced')]),
        ),
    ]
