# Generated by Django 2.2.17 on 2021-02-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0019_auto_20210220_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='map',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'The Skeld'), (2, 'Polus'), (3, 'MiraHQ'), (4, 'The Airship')], null=True),
        ),
    ]
