# Generated by Django 2.2.17 on 2021-02-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0020_auto_20210220_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='published',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
