# Generated by Django 2.2.17 on 2022-02-10 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0024_room_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='map',
            new_name='game_map',
        ),
        migrations.AlterField(
            model_name='room',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'beginner'), (2, 'medium'), (3, 'advanced')]),
        ),
        migrations.AlterField(
            model_name='room',
            name='players_number',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(15)]),
        ),
        migrations.AlterField(
            model_name='room',
            name='searched_players_number',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(14)]),
        ),
    ]
