# Generated by Django 2.2.17 on 2020-12-08 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='level_of_advancement',
        ),
    ]
